<?php
// Edit ONLY these 4 variables
// Do not edit this file in any other way if you do not know what you are doing
DEFINE ('DB_SERVER', 'srv');
DEFINE ('DB_USER', 'usr');
DEFINE ('DB_PASS', 'pass');
DEFINE ('DB_NAME', 'db');
$mysqli = new mysqli(DB_SERVER, DB_USER, DB_PASS, DB_NAME);
